dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r backend/requirements.txt
  - pip install psycopg2 --quiet
  - pip install codecov
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE overworld;" -U postgres  
script:
  - python backend/manage.py migrate
  - python backend/manage.py test actions games users
after_success:
  - codecov
